"""India state and territory names with official agriculture department links."""

STATES = [
    "Andhra Pradesh", "Arunachal Pradesh", "Assam", "Bihar", "Chhattisgarh", "Goa",
    "Gujarat", "Haryana", "Himachal Pradesh", "Jharkhand", "Karnataka", "Kerala",
    "Madhya Pradesh", "Maharashtra", "Manipur", "Meghalaya", "Mizoram", "Nagaland",
    "Odisha", "Punjab", "Rajasthan", "Sikkim", "Tamil Nadu", "Telangana", "Tripura",
    "Uttar Pradesh", "Uttarakhand", "West Bengal", "Andaman and Nicobar Islands",
    "Chandigarh", "Dadra and Nagar Haveli and Daman and Diu", "Delhi", "Jammu and Kashmir",
    "Ladakh", "Lakshadweep", "Puducherry",
]

# Department links are drawn from APEDA Farmer Connect's state/UT directory.
STATE_AGRICULTURE_PORTALS = {
    "Andhra Pradesh": "https://www.apagrisnet.gov.in/",
    "Arunachal Pradesh": "https://www.agri.arunachal.gov.in/",
    "Assam": "https://agri-horti.assam.gov.in/",
    "Bihar": "https://dbtagriculture.bihar.gov.in/",
    "Chhattisgarh": "https://agriportal.cg.nic.in/horticulture/HortiEn/Default.aspx",
    "Goa": "https://agri.goa.gov.in/",
    "Gujarat": "https://agri.gujarat.gov.in/",
    "Haryana": "https://agriharyana.gov.in/",
    "Himachal Pradesh": "https://agriculture.hp.gov.in/en/home-english/",
    "Jammu and Kashmir": "https://apd.jk.gov.in/index.html",
    "Jharkhand": "https://www.jharkhand.gov.in/agriculture",
    "Karnataka": "https://karnataka.mygov.in/en",
    "Kerala": "https://www.keralaagriculture.gov.in/",
    "Lakshadweep": "https://lakshadweep.gov.in/departments/agriculture/",
    "Madhya Pradesh": "https://mpkrishi.mp.gov.in/",
    "Maharashtra": "https://krishi.maharashtra.gov.in/",
    "Manipur": "https://agrimanipur.mn.gov.in/",
    "Meghalaya": "https://megagriculture.gov.in/",
    "Mizoram": "https://agriculturemizoram.nic.in/",
    "Nagaland": "https://agriculture.nagaland.gov.in/",
    "Odisha": "https://agri.odisha.gov.in/",
    "Puducherry": "https://agri.py.gov.in/",
    "Punjab": "https://agri.punjab.gov.in/",
    "Rajasthan": "https://agriculture.rajasthan.gov.in/home",
    "Sikkim": "https://agri.sikkim.gov.in/",
    "Tamil Nadu": "https://www.tnagrisnet.tn.gov.in/",
    "Telangana": "https://agri.telangana.gov.in/",
    "Tripura": "https://agri.tripura.gov.in/",
    "Uttar Pradesh": "https://agriculture.up.gov.in/",
    "Uttarakhand": "https://agriculture.uk.gov.in/",
    "West Bengal": "https://wb.gov.in/portal/web/guest/agriculture",
    "Andaman and Nicobar Islands": "https://agri.andamannicobar.gov.in/",
    "Dadra and Nagar Haveli and Daman and Diu": "https://ddd.gov.in/Departments/Agriculture.aspx",
    "Delhi": "https://agriwelfare.gov.in/",
    "Chandigarh": "https://agri.punjab.gov.in/",
}

STATE_NAMES_HI = {
    "Andhra Pradesh": "आंध्र प्रदेश", "Arunachal Pradesh": "अरुणाचल प्रदेश", "Assam": "असम",
    "Bihar": "बिहार", "Chhattisgarh": "छत्तीसगढ़", "Goa": "गोवा", "Gujarat": "गुजरात",
    "Haryana": "हरियाणा", "Himachal Pradesh": "हिमाचल प्रदेश", "Jharkhand": "झारखंड",
    "Karnataka": "कर्नाटक", "Kerala": "केरल", "Madhya Pradesh": "मध्य प्रदेश",
    "Maharashtra": "महाराष्ट्र", "Manipur": "मणिपुर", "Meghalaya": "मेघालय",
    "Mizoram": "मिज़ोरम", "Nagaland": "नागालैंड", "Odisha": "ओडिशा", "Punjab": "पंजाब",
    "Rajasthan": "राजस्थान", "Sikkim": "सिक्किम", "Tamil Nadu": "तमिलनाडु",
    "Telangana": "तेलंगाना", "Tripura": "त्रिपुरा", "Uttar Pradesh": "उत्तर प्रदेश",
    "Uttarakhand": "उत्तराखंड", "West Bengal": "पश्चिम बंगाल",
    "Andaman and Nicobar Islands": "अंडमान और निकोबार द्वीपसमूह", "Chandigarh": "चंडीगढ़",
    "Dadra and Nagar Haveli and Daman and Diu": "दादरा और नगर हवेली और दमन और दीव",
    "Delhi": "दिल्ली", "Jammu and Kashmir": "जम्मू और कश्मीर", "Ladakh": "लद्दाख",
    "Lakshadweep": "लक्षद्वीप", "Puducherry": "पुदुचेरी",
}
