apiVersion: v1
kind: Secret
metadata:
  name: kisan-bhai-secrets
  namespace: kisan-bhai
  annotations:
    avp.kubernetes.io/path: secret/data/kisan-bhai/app
    argocd.argoproj.io/sync-wave: "-1"
type: Opaque
stringData:
  MYSQL_DATABASE: <MYSQL_DATABASE>
  MYSQL_USER: <MYSQL_USER>
  MYSQL_PASSWORD: <MYSQL_PASSWORD>
  MYSQL_ROOT_PASSWORD: <MYSQL_ROOT_PASSWORD>
  SECRET_KEY: <SECRET_KEY>
  OPENWEATHER_API_KEY: <OPENWEATHER_API_KEY>
---
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
  annotations:
    avp.kubernetes.io/path: secret/data/kisan-bhai/cloudflare
    argocd.argoproj.io/sync-wave: "-1"
type: Opaque
stringData:
  api-token: <api-token>
---
apiVersion: v1
kind: Secret
metadata:
  name: cloudflared
  namespace: cloudflare-tunnel
  annotations:
    avp.kubernetes.io/path: secret/data/kisan-bhai/cloudflared
    argocd.argoproj.io/sync-wave: "-1"
type: Opaque
stringData:
  TUNNEL_TOKEN: <TUNNEL_TOKEN>
